#### SpringBoot config
spring:
  main:
    show_banner: true

endpoints:
  enabled: false
  health:
    enabled: true
    sensitive: false
  metrics:
    enabled: true
    sensitive: false
  shutdown:
    enabled: true
  env:
    enabled: true
  autoconfig:
    enabled: true
  beans:
    enabled: true
  info:
    enabled: true
    sensitive: false

#### Server settings
server:
  port: 8080
management:
  port: 8081
  add-application-context-header: false
  security:
    enabled: true
    